## 2.1 数据操作

In [2]:
import torch

### 创建张量

In [12]:
# 一维张量
x1 = torch.arange(12)
# 二维张量
x2 = torch.arange(12).reshape(3, 4)
# 三维张量
x3 = torch.arange(24).reshape(2, 3, 4)

# 全0张量
y0 = torch.zeros((2, 3))
# 全1张量
y1 = torch.ones((2, 3))
# 随机张量
y2_1 = torch.rand(2, 3)  # [0, 1)均匀分布随机数
y2_2 = torch.randn(2, 3) # 均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。
# 从列表创建张量
y3 = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("x1:", x1)
print("x2:", x2)
print("x3:", x3)
print("y0:", y0)
print("y1:", y1)
print("y2_1:", y2_1)
print("y2_2:", y2_2)
print("y3:", y3)

x1: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
x2: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
x3: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
y0: tensor([[0., 0., 0.],
        [0., 0., 0.]])
y1: tensor([[1., 1., 1.],
        [1., 1., 1.]])
y2_1: tensor([[0.7782, 0.1913, 0.1020],
        [0.4966, 0.2148, 0.6055]])
y2_2: tensor([[ 0.5881, -1.5270, -0.3020],
        [-0.9857,  1.2315, -1.2538]])
y3: tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

查看形状

In [3]:
x.shape

torch.Size([12])

张量中元素总数

In [4]:
x.numel()

12

改变形状

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### 运算符

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

元素级操作也可应用于张量

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
torch.exp(x) # 即tensor([e^1, e^2, e^4, e^8])

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量连结
cat函数：dim参数指定连结的轴
- 默认值为0，即按行连结
- 默认值为1，即按列连结
- 默认值为2，即按深度连结

In [41]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
# 相等运算符
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x == y # x 与 y 的大小必须相等

tensor([False,  True, False, False])

In [17]:
# 求和运算符
x = torch.tensor([1.0, 2, 4, 8])
x.sum()

tensor(15.)

### 广播机制
两个大小不同的张量进行元素级操作时，会自动根据广播机制将大小不同的张量**暂时**转换为相同的大小（实际不会改变原张量的大小）

In [18]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

```python
a = tensor([[0, 0],
            [1, 1],
            [2, 2]])

b = tensor([[0, 1],
            [0, 1],
            [0, 1]])

a + b = tensor([[0, 1],
                [1, 2],
                [2, 3]])
```

### 索引与切片
X[行索引, 列索引]<br>
- -1表示最后一个

In [22]:
X = torch.arange(12).reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [24]:
X[-1], X[1:3] # 即 X[-1, :], X[1:3, :] [1, 3)左开右闭

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

赋值

In [25]:
X[0:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 节省内存

In [27]:
X = torch.arange(12).reshape(3, 4)
Y = torch.zeros(3, 4)

before = id(Y) # id类似C++的指针，指向Y的内存地址
Y = X + Y
after = id(Y)
before == after

False

运行一些操作可能会导致为新结果分配内存 <br>
`Y = X + Y` 后，Y的内存地址会改变 <br>
这会造成内存的浪费<br>
使用 `X[:] = X + Y` 或 `X += Y` 可以减少操作的内存开销

In [28]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1856127586752
id(Z): 1856127586752

- `Z[:]` 选中 `Z` 的全部元素，但仍然是原来的 `Z` 
- `Z[:] = X + Y`: 计算 `X + Y` ，然后把结果复制到 `Z` 原来的内存空间里。

但是依然会分配新的内存空间（`X + Y` 会被计算出来, 然后复制到 `Z` 原来的内存空间里）

In [29]:
torch.add(X, Y, out=Z)
Z

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.]])

### 转换Python对象

In [30]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [31]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.2 数据预处理

### 读取数据集

In [32]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

```[markdown]
.   当前目录
..  上一级目录
./  当前目录下
../ 上一级目录下
```

In [34]:
import pandas as pd

data = pd.read_csv(data_file)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

### 处理缺失值
`NAN` 表示缺失值
`iloc` 方法用于根据索引选择数据

In [ ]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True)) # 只对数值型NaN填充均值
inputs

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

`get_dummies` 方法用于将分类变量转换为独热编码<br>
把 Alley 展开成多列：

In [39]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

### 转换为张量形式

In [ ]:
import torch

# 先将 pandas.DataFrame 转换为 numpy.ndarray 数组，再转换为 torch.tensor 张量
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## 2.3 线性代数

通常使用 `tensor` 来表示矩阵和向量。

In [52]:
A = torch.arange(12).reshape((3, 4))
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### 矩阵转置 `A.T`

In [53]:
A.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [54]:
A3 = torch.arange(24).reshape((2, 3, 4))
print(A3.shape, A3.T.shape)
A3, A3.T

torch.Size([2, 3, 4]) torch.Size([4, 3, 2])

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 0, 12],
          [ 4, 16],
          [ 8, 20]],

         [[ 1, 13],
          [ 5, 17],
          [ 9, 21]],

         [[ 2, 14],
          [ 6, 18],
          [10, 22]],

         [[ 3, 15],
          [ 7, 19],
          [11, 23]]]))

转置函数会将所有轴的维度逆序反转：<br>
(2, 3, 4) -> (4, 3, 2) <br>
计算步骤：`A3.T[k, j, i] = A3[i, j, k]`<br>
```
A3.T[0, 0, 0] = A3[0, 0, 0] = 0
A3.T[0, 0, 1] = A3[1, 0, 0] = 12

A3.T[0, 1, 0] = A3[0, 1, 0] = 4
A3.T[0, 1, 1] = A3[1, 1, 0] = 16

A3.T[0, 2, 0] = A3[0, 2, 0] = 8
A3.T[0, 2, 1] = A3[1, 2, 0] = 20
```

In [55]:
# torch 没有一维列向量
C = torch.tensor([1, 2])
C, C.T, C == C.T

(tensor([1, 2]), tensor([1, 2]), tensor([True, True]))

In [56]:
# 列向量只能表示为 
D = torch.tensor([[1],
                  [2]])
D, D.T, D == D.T

(tensor([[1],
         [2]]),
 tensor([[1, 2]]),
 tensor([[ True, False],
         [False,  True]]))

关于**张量**的解释：<br>
张量指代数对象<br>
- 向量是一阶张量<br>
- 矩阵是二阶张量<br>
- 等等

### 张量克隆 `A.clone()`

In [57]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A == B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### 哈达玛积 `A * B`
$A \odot B$ <br>
Hadamard product，也称为元素级乘法，是两个张量对应元素相乘的结果。<br>
`shape` 必须相同。

In [58]:
A = torch.arange(20).reshape(5, 4)
B = A.clone()
A, B, A * B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121],
         [144, 169, 196, 225],
         [256, 289, 324, 361]]))

### 求和 `torch.sum`

#### 降维求和

In [61]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

`axis` 表示操作的轴，默认值为 0 。
- `A.sum(axis=0)` 即对 `A` 的第 0 个轴（列）求和。
- `A.sum(axis=1)` 即对 `A` 的第 1 个轴（行）求和。

In [62]:
A = torch.tensor([[1, 2],
                  [3, 4]])
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([4, 6]), torch.Size([2]))

In [63]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([3, 7]), torch.Size([2]))

In [64]:
B = torch.arange(24).reshape((2, 3, 4))
print("B:", B)
print("B.sum(axis=0):", B.sum(axis=0))
print("B.sum(axis=1):", B.sum(axis=1))
print("B.sum(axis=2):", B.sum(axis=2))
print("B.sum():", B.sum())

B: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
B.sum(axis=0): tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
B.sum(axis=1): tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
B.sum(axis=2): tensor([[ 6, 22, 38],
        [54, 70, 86]])
B.sum(): tensor(276)

- `axis=0`: 对第 0 个轴（通道/几个矩阵）求和。
- `axis=1`: 对第 1 个轴（行）求和。
- `axis=2`: 对第 2 个轴（列）求和。
- `axis=None`: 对所有轴求和。

In [65]:
print("B.sum(axis=0,1):", B.sum(axis=(0, 1)))

B.sum(axis=0,1): tensor([60, 66, 72, 78])

axis=(0, 1)：先对第 0 个轴（通道/几个矩阵）求和，再对第 1 个轴（行）求和。

#### 非降维求和（keepdims = True）

In [71]:
A = torch.arange(12).reshape(3, 4)
sum_A_axis_0 = A.sum(axis=0, keepdims=True)
sum_A_axis_1 = A.sum(axis=1, keepdims=True)

A, sum_A_axis_0, sum_A_axis_1

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[12, 15, 18, 21]]),
 tensor([[ 6],
         [22],
         [38]]))

### 均值 `A.mean()`

In [68]:
A = torch.randn(3, 4)
A, A.mean(axis=0)

(tensor([[-1.5295, -0.0408,  0.8069, -0.8095],
         [-0.3255, -1.7654, -0.6101,  0.0896],
         [ 0.3848, -1.6780,  0.0419, -1.3636]]),
 tensor([-0.4901, -1.1614,  0.0796, -0.6945]))

### 点积 (torch.dot)
$$\mathbf{x}^\top\mathbf{y}$$

In [74]:
y = torch.ones(4)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

### 矩阵-向量积（torch.mv）
$$\begin{split}\mathbf{A}\mathbf{x}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix}\mathbf{x}
= \begin{bmatrix}
 \mathbf{a}^\top_{1} \mathbf{x}  \\
 \mathbf{a}^\top_{2} \mathbf{x} \\
\vdots\\
 \mathbf{a}^\top_{m} \mathbf{x}\\
\end{bmatrix}\end{split}$$

`torch.mv(A, x)` 是专用于矩阵和向量积的函数<br>
而 `torch.matmul(A, x)`、`A @ x`和`torch.mm(A, x)`  则是通用的矩阵乘法函数，可以处理任意维度的矩阵和向量。

### 矩阵乘法 `A @ B`
$C = A \cdot B$ <br>
$C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}$

In [ ]:
A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[10, 20],
                  [30, 40]])
A * B

tensor([[ 10,  40],
        [ 90, 160]])

In [ ]:
C = torch.tensor([1, 2])
C, C.T, C == C.T

(tensor([1, 2]), tensor([1, 2]), tensor([True, True]))

### 范数（torch.norm）
用于衡量一个张量的大小或长度,即从原点到该点的距离。<br>
**深度学习中，通常用于最大化概率/最小化预测与目标之间的距离等**

#### L1 范数
所有元素绝对值之和，也叫曼哈顿距离。
$$
\| \mathbf{x} \|_1 = \sum_{i=1}^{n} |x_i|
$$
```python
torch.norm(x, p=1)
```

In [ ]:
x = torch.tensor([2, 3, 4], dtype=torch.float32)
torch.norm(x, p=1)

tensor(9.)

注意范数计算需要浮点数类型，否则会报错。

#### L2 范数
向量各元素平方和再开根号，也叫欧几里得距离。
$$
\| \mathbf{x} \|_2 = \sqrt{\sum_{i=1}^{n} x_i^2}
$$
```python
torch.norm(x) # 默认计算 L2 范数
torch.norm(x, p=2)
```

In [80]:
x = torch.tensor([2, 3, 4], dtype=torch.float32)
torch.norm(x, p=2)

tensor(5.3852)

#### F范数
就是 L2 范数在矩阵上的推广。
$$
\| \mathbf{A} \|_F = \sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}^2}
$$
```python
torch.norm(A)
```

In [81]:
x = torch.arange(10, dtype=torch.float32).reshape(2, 5)
torch.norm(x, p=2)

tensor(16.8819)

## 2.4 微积分
考研数学难度，略<br>
https://zh-v2.d2l.ai/chapter_preliminaries/calculus.html

## 2.5 自动微分

### 求导

计算 $y = 2x^{T}x$ 的关于列向量 `x` 求导

In [88]:
x = torch.arange(4.0, requires_grad=True)
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), None)

In [89]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [90]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

`y.backward()` 是反向传播，它会自动计算 `y` 对所有 `requires_grad=True` 的变量的梯度，结果存在 `.grad` 里。

### 求偏导

只计算 $z$ 对 $x$ 的偏导，将 $y$ 的计算图切断（视为常数），只保留 $z$ 的计算图。

$$
y = x^2 \\
z = x^3 \\
令 u = y = x^2，则 u = u * x。\\
$$

In [91]:
x.grad.zero_()     # 清空之前的梯度
y = x * x          # y = x²，保留了计算图
u = y.detach()     # u 的值等于 y，但切断了计算图（PyTorch 把 u 当常数）
z = u * x          # z = u · x，u 被当作常数

In [92]:
z.sum().backward()  # 反向传播
x.grad == u

tensor([True, True, True, True])

故 `y` 对 `x` 的偏导为 $u$。

另一种方法：直接在 `y` 上调用反向传播

In [93]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])