## 2.1 数据操作

In [1]:
import torch

### 创建张量

In [12]:
# 一维张量
x1 = torch.arange(12)
# 二维张量
x2 = torch.arange(12).reshape(3, 4)
# 三维张量
x3 = torch.arange(24).reshape(2, 3, 4)

# 全0张量
y0 = torch.zeros((2, 3))
# 全1张量
y1 = torch.ones((2, 3))
# 随机张量
y2_1 = torch.rand(2, 3)  # [0, 1)均匀分布随机数
y2_2 = torch.randn(2, 3) # 均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。
# 从列表创建张量
y3 = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("x1:", x1)
print("x2:", x2)
print("x3:", x3)
print("y0:", y0)
print("y1:", y1)
print("y2_1:", y2_1)
print("y2_2:", y2_2)
print("y3:", y3)

x1: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
x2: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
x3: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
y0: tensor([[0., 0., 0.],
        [0., 0., 0.]])
y1: tensor([[1., 1., 1.],
        [1., 1., 1.]])
y2_1: tensor([[0.7782, 0.1913, 0.1020],
        [0.4966, 0.2148, 0.6055]])
y2_2: tensor([[ 0.5881, -1.5270, -0.3020],
        [-0.9857,  1.2315, -1.2538]])
y3: tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

查看形状

In [3]:
x.shape

torch.Size([12])

张量中元素总数

In [4]:
x.numel()

12

改变形状

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### 运算符

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

元素级操作也可应用于张量

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
torch.exp(x) # 即tensor([e^1, e^2, e^4, e^8])

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量连结
cat函数：dim参数指定连结的轴
- 默认值为0，即按行连结
- 默认值为1，即按列连结
- 默认值为2，即按深度连结

In [41]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
# 相等运算符
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x == y # x 与 y 的大小必须相等

tensor([False,  True, False, False])

In [17]:
# 求和运算符
x = torch.tensor([1.0, 2, 4, 8])
x.sum()

tensor(15.)

### 广播机制
两个大小不同的张量进行元素级操作时，会自动根据广播机制将大小不同的张量**暂时**转换为相同的大小（实际不会改变原张量的大小）

In [18]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

```python
a = tensor([[0, 0],
            [1, 1],
            [2, 2]])

b = tensor([[0, 1],
            [0, 1],
            [0, 1]])

a + b = tensor([[0, 1],
                [1, 2],
                [2, 3]])
```

### 索引与切片
X[行索引, 列索引]<br>
- -1表示最后一个

In [22]:
X = torch.arange(12).reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [24]:
X[-1], X[1:3] # 即 X[-1, :], X[1:3, :] [1, 3)左开右闭

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

赋值

In [25]:
X[0:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 节省内存

In [27]:
X = torch.arange(12).reshape(3, 4)
Y = torch.zeros(3, 4)

before = id(Y) # id类似C++的指针，指向Y的内存地址
Y = X + Y
after = id(Y)
before == after

False

运行一些操作可能会导致为新结果分配内存 <br>
`Y = X + Y` 后，Y的内存地址会改变 <br>
这会造成内存的浪费<br>
使用 `X[:] = X + Y` 或 `X += Y` 可以减少操作的内存开销

In [28]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1856127586752
id(Z): 1856127586752

- `Z[:]` 选中 `Z` 的全部元素，但仍然是原来的 `Z` 
- `Z[:] = X + Y`: 计算 `X + Y` ，然后把结果复制到 `Z` 原来的内存空间里。

但是依然会分配新的内存空间（`X + Y` 会被计算出来, 然后复制到 `Z` 原来的内存空间里）

In [29]:
torch.add(X, Y, out=Z)
Z

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.]])

### 转换Python对象

In [30]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [31]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.2 数据预处理

### 读取数据集

In [32]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

```[markdown]
.   当前目录
..  上一级目录
./  当前目录下
../ 上一级目录下
```

In [34]:
import pandas as pd

data = pd.read_csv(data_file)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

### 处理缺失值
`NAN` 表示缺失值
`iloc` 方法用于根据索引选择数据

In [ ]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True)) # 只对数值型NaN填充均值
inputs

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

`get_dummies` 方法用于将分类变量转换为独热编码<br>
把 Alley 展开成多列：

In [39]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

### 转换为张量形式

In [ ]:
import torch

# 先将 pandas.DataFrame 转换为 numpy.ndarray 数组，再转换为 torch.tensor 张量
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))